use_frameworks!

target 'VerticallyButton_Example' do
  pod 'VerticallyButton', :path => '../'
end

target 'VerticallyButton_Tests' do
    pod 'VerticallyButton', :path => '../'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
    pod 'Quick', '~> 1.0.0'
end
